# Generated by Django 4.1.6 on 2023-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_beammodel_delete_beam_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
            ],
        ),
    ]
