# Generated by Django 4.1.6 on 2023-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
            ],
        ),
    ]
