# Generated by Django 4.1.6 on 2023-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField()),
                ('z', models.TextField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
            ],
        ),
    ]
